name: Check for Updates

on:
  schedule:
    - cron: '0 */12 * * *'  # 每12小时检查一次
  workflow_dispatch:      # 允许手动触发

jobs:
  check-and-update:
    runs-on: macos-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      
    - name: Install jq
      run: |
        brew install jq
      
    - name: Check libmaxminddb for updates
      id: check
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        # 获取最新版本
        echo "Fetching latest version from GitHub API..."
        API_RESPONSE=$(curl -s -H "Authorization: token $GITHUB_TOKEN" https://api.github.com/repos/maxmind/libmaxminddb/releases/latest)
        echo "API Response: $API_RESPONSE"
        LATEST_VERSION=$(echo "$API_RESPONSE" | grep -o '"tag_name": *"[^"]*"' | cut -d'"' -f4)
        
        # 移除版本号前的 'v' 如果存在
        LATEST_VERSION=${LATEST_VERSION#v}
        
        # 使用硬编码的当前版本
        CURRENT_VERSION="1.12.1"
        
        echo "Latest version from API: $LATEST_VERSION"
        echo "Current version: $CURRENT_VERSION"
        
        if [ "$LATEST_VERSION" = "$CURRENT_VERSION" ]; then
          echo "No updates available"
          echo "update_needed=false" >> $GITHUB_OUTPUT
          exit 0
        fi
        
        # 克隆并更新源码
        git clone https://github.com/maxmind/libmaxminddb.git temp
        if [ $? -ne 0 ]; then
            echo "Failed to clone repository"
            exit 1
        fi
        
        cd temp
        if [ $? -ne 0 ]; then
            echo "Failed to change directory"
            exit 1
        fi
        
        git checkout $LATEST_VERSION
        if [ $? -ne 0 ]; then
            echo "Failed to checkout version: $LATEST_VERSION"
            cd ..
            rm -rf temp
            exit 1
        fi
        
        # 删除旧版本
        rm -rf "../Sources/CLibMaxMindDB/libmaxminddb-${CURRENT_VERSION}"
        
        # 复制所有必需文件
        mkdir -p "../Sources/CLibMaxMindDB/libmaxminddb-${LATEST_VERSION#v}/include"
        mkdir -p "../Sources/CLibMaxMindDB/libmaxminddb-${LATEST_VERSION#v}/src"
        
        # 复制源文件
        cp src/maxminddb.c "../Sources/CLibMaxMindDB/libmaxminddb-${LATEST_VERSION#v}/src/"
        cp src/data-pool.c "../Sources/CLibMaxMindDB/libmaxminddb-${LATEST_VERSION#v}/src/"
        
        # 复制头文件
        cp include/maxminddb.h "../Sources/CLibMaxMindDB/libmaxminddb-${LATEST_VERSION#v}/include/"
        
        # 复制内部头文件
        cp src/data-pool.h "../Sources/CLibMaxMindDB/libmaxminddb-${LATEST_VERSION#v}/src/"
        cp src/maxminddb-compat-util.h "../Sources/CLibMaxMindDB/libmaxminddb-${LATEST_VERSION#v}/src/"
        
        # 更新配置文件
        cat > "../Sources/CLibMaxMindDB/libmaxminddb-${LATEST_VERSION#v}/include/maxminddb_config.h" << EOF
        #ifndef MAXMINDDB_CONFIG_H
        #define MAXMINDDB_CONFIG_H
        
        #define PACKAGE_VERSION "${LATEST_VERSION#v}"
        
        #ifndef _WIN32
        #define HAVE_MMAP 1
        #endif
        
        #endif
        EOF
        
        cd ..
        rm -rf temp
        
        # 设置版本号
        echo "LIBMAXMINDDB_VERSION=$LATEST_VERSION" >> $GITHUB_ENV
        VERSION="1.0.${GITHUB_RUN_NUMBER}"
        echo "VERSION=$VERSION" >> $GITHUB_ENV
        echo "update_needed=true" >> $GITHUB_OUTPUT
        
        # 更新 Package.swift
        sed -i '' "s/libmaxminddb-[0-9.][0-9.]*\/src/libmaxminddb-${LATEST_VERSION#v}\/src/g" Package.swift
        sed -i '' "s/libmaxminddb-[0-9.][0-9.]*\/include/libmaxminddb-${LATEST_VERSION#v}\/include/g" Package.swift
        
        # 更新 module.modulemap
        sed -i '' "s/libmaxminddb-[0-9.][0-9.]*\/include/libmaxminddb-${LATEST_VERSION#v}\/include/g" Sources/CLibMaxMindDB/module.modulemap
        
        # 更新 workflow 文件中的版本号
        sed -i '' "s/CURRENT_VERSION=\"[0-9.]*\"/CURRENT_VERSION=\"${LATEST_VERSION#v}\"/g" .github/workflows/update-check.yml
        
        echo "LATEST_VERSION: $LATEST_VERSION"
        echo "LIBMAXMINDDB_VERSION: $LIBMAXMINDDB_VERSION"

    - name: Commit updates
      if: steps.check.outputs.update_needed == 'true'
      env:
        GITHUB_TOKEN: ${{ secrets.PAT }}
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add Sources/CLibMaxMindDB/ Package.swift
        git commit -m "Update libmaxminddb to version ${{ env.LIBMAXMINDDB_VERSION }}"
        git push
        
        # 使用 GitHub API 更新 workflow 文件
        WORKFLOW_CONTENT=$(cat .github/workflows/update-check.yml | base64)
        CURRENT_SHA=$(curl -s -H "Authorization: token $GITHUB_TOKEN" \
          "https://api.github.com/repos/SunboyGo/MaxMindDBSwift/contents/.github/workflows/update-check.yml" \
          | jq -r .sha)
        
        curl -X PUT \
          -H "Authorization: token $GITHUB_TOKEN" \
          -H "Accept: application/vnd.github.v3+json" \
          https://api.github.com/repos/SunboyGo/MaxMindDBSwift/contents/.github/workflows/update-check.yml \
          -d "{
            \"message\": \"Update workflow version to ${{ env.LIBMAXMINDDB_VERSION }}\",
            \"content\": \"$WORKFLOW_CONTENT\",
            \"sha\": \"$CURRENT_SHA\",
            \"branch\": \"main\"
          }"
        
        # 创建标签
        git tag ${{ env.VERSION }}
        git push --tags

    - name: Create Release
      if: steps.check.outputs.update_needed == 'true'
      uses: softprops/action-gh-release@v1
      with:
        tag_name: ${{ env.VERSION }}
        name: Release ${{ env.VERSION }}
        body: |
          Updated to libmaxminddb version ${{ env.LIBMAXMINDDB_VERSION }}
          
          ### Changes
          - Updated libmaxminddb source code to version ${{ env.LIBMAXMINDDB_VERSION }}
          
          ### Installation
          ```swift
          dependencies: [
              .package(url: "https://github.com/SunboyGo/MaxMindDBSwift.git", from: "${{ env.VERSION }}")
          ]
          ```
      env:
        GITHUB_TOKEN: ${{ secrets.PAT }} 
